### ISSUE TITLE
Nav Menu

### ISSUE THREAD

**Issue by scottfuoco** [redacademy/cinderella-fall-2016#14]
Change 
- Title menu color: $color_background_4 - DONE
- Weight of title bar text: light - DONE
- Font-size of title bar text: 17px - DONE
- Nav Menu font-size: 21px;- DONE
- Nav Menu font-weight: light - DONE
- change close menu icon - done
- change open hamburger icon - done
- change privacy protection icon - done

**Comment by ssamuels0916** [comment]
just need to add icons

**Comment by ssamuels0916** [comment]
resolved
