### ISSUE TITLE
Create a unique, project-specific prefix for your funcitons

### ISSUE THREAD

**Issue by mandiwise** [redacademy/cinderella-fall-2016#2]
In your functionality plugin (post-types.php and taxonomies.php), and your theme (functions.php and extras.php), please re-prefix all of your functions consistently. Some are prefixed "red_starter_", and some "my_".

Please use "cinderella_" (or "cp_"...or something else relevant) as a function prefix throughout your project instead.

**Comment by ssamuels0916** [comment]
Thanks, resolved
